### ISSUE TITLE
Code Actions On Save not working.

### ISSUE THREAD

**Issue by mjmatthiesen** [anzwdev/al-code-outline#213] opened 2021-02-18 23:01 UTC
base vc setting Format on Save: True (confirmed that workspace, language, project setting is all true)
![image](https://user-images.githubusercontent.com/16603906/108432933-63839180-7202-11eb-9cd6-91368b8acbd6.png)
Nothing is triggering and the code action in the file is gone, so I seemingly cannot manually trigger it.

**Comment by anzwdev** [comment] 2021-02-21 14:56
Could you check if you have one of these settings in your vs code settings:

```
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
```

or

```
    "editor.codeActionsOnSave": {
        "source.fixAll.al": true
    },
```

**Comment by mjmatthiesen** [comment] 2021-02-23 18:23
That resolves it, thank you.

It would still be nice to keep the code action on the page, even if I have it turned on for on save, but that might just be my preference.

**Comment by mjmatthiesen** [comment] 2021-02-23 20:23
So I had closed this issue, but this action is having a negative side effect. I am using it only to sort properties. When I save a codeunit, it will remove empty lines that I added.

As an example:
```
//xyz::begin
doSomething();
//xyz::end

doMore();
```

It will remove the blank line before doMore.


This only happens when it's enabled, if I disable it, it doesn't happen. If I trigger the action separately, it doesn't happen.

**Comment by anzwdev** [comment] 2021-06-13 21:46
Hi

I've released a new version of the extension, this issue should be fixed now. The problem was caused by running document formatter twice. It was first run by the code action and then by visual studio code during document save. I've changed the logic and when code action is run on document save, it no longer runs the formatter.

**Comment by mjmatthiesen** [comment] 2021-06-21 19:05
This appears to be resolved and working correctly now.

It would be nice if I could still manually trigger the action instead of having to rely on the save.

**Closed** 2021-06-21 19:05 UTC
Labels: bug, released
