### ISSUE TITLE
Cannot Open Countries/Regions 20.0.37253.39075

### ISSUE THREAD

**Issue by gbrault** [anzwdev/al-code-outline#359] opened 2022-04-23 05:48 UTC
Hello, when double click on Countries/Regions, I get the error seen in the next picture
AZ AL Dev Tools/AL Code Outline: v3.0.31
![image](https://user-images.githubusercontent.com/7886676/164879558-1e083799-31ea-4c1b-b5b4-d7244c7dfe7f.png)
![image](https://user-images.githubusercontent.com/7886676/164879598-f662f843-24a8-4fb0-b7cc-2bb6fa9f533b.png)

**Comment by rvanbekkum** [comment] 2022-04-23 08:22
Same issue as https://github.com/anzwdev/al-code-outline/issues/355? :)

**Comment by gbrault** [comment] 2022-04-23 09:26
@rvanbekkum : thanks for the feedback, I hope for you they are all the same!

You have the same for Country/Region

Error message is the same:

cannot open al-preview://allang/AL%20for%20BC%20Sandbox/Table/9/Country/Region.dal. Detail: Unable to resolve text model content for resource al-preview://allang/AL%20for%20BC%20Sandbox/Table/9/Country/Region.dal

Maybe they are also some others! I will report there if found.

**Comment by anzwdev** [comment] 2022-04-23 16:38
Yes, it is a duplicate of issue #355. I've fixed the issue and release a new version of the extension.

**Comment by gbrault** [comment] 2022-04-23 16:39
Mainy thanks @anzwdev !

**Closed by anzwdev** 2022-04-23 16:38 UTC
