### ISSUE TITLE
[Question] Variable completion

### ISSUE THREAD

**Issue by fvet** [anzwdev/al-code-outline#415] opened 2022-10-27 09:18 UTC
In below scenario, the variable completion provider suggests the object names correctly if I search for objects that **start** with the variable name.

`SalesHeader` > "Sales Header", `ICDataStore` > "IC Datastore" (without prefix)

The variable completion provider seems to support search for **part** of the variable name as well. 

`Header` > "Sales Header" is listed in the suggested objects (somewhat lower, but OK)

However

`DataStore` does no longer list the "IC Datastore" object?

![Completion](https://user-images.githubusercontent.com/25268332/198244255-1ace6a3e-7af5-40c0-a0b2-9a7a7f01891c.gif)

**Comment by anzwdev** [comment] 2022-12-17 14:22
Problem will be partially solved by the #425 fix. 

The suggestions generated currently by my extension are only allowing vscode to match them by the variable name, but I've decided to removed that rule as #425 fix. Now whole suggested entry (variable name + data type) will be used. 

Your issue is caused by the default value of `"editor.suggest.matchOnWordStartOnly": true` VS Code setting. Because current version of my extension allows VS Code to match on "ICDatastore" part only, that setting is preventing the match ("ICD" is treated as a single word). With the new version, VS Code will also look at the data type part ("ID Datastore") so will be able to find it.

**Closed** 2023-02-12 14:31 UTC
Labels: released, setup
